from typing import Dict, List
def evaluate_weights(artifact_uri: str, dataset_id: str) -> Dict[str, float]: ...
def aggregate_scores(score_rows: List[dict]) -> dict:
    # e.g., weighted average, median-of-means, tie-break rules
    ...
