from pathlib import Path

def serialize_weights(model, layers: list[int]) -> bytes: ...
def compress(blob: bytes) -> bytes: ...
def sign(blob: bytes, private_key: bytes) -> bytes: ...
def save_artifact(blob: bytes, dest: Path) -> Path: ...